// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrZUnCmFcZI22xj2D1jPnGxmmA9Fusr8U',
    appId: '1:805423906733:web:7dbb8cce7424ec1941ab24',
    messagingSenderId: '805423906733',
    projectId: 'gram-yatra-cb95d',
    authDomain: 'gram-yatra-cb95d.firebaseapp.com',
    storageBucket: 'gram-yatra-cb95d.firebasestorage.app',
    measurementId: 'G-0PR05NXF82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYnRkRBK3jVNp4bmYfP66Pm7ExNKxq4_s',
    appId: '1:805423906733:android:3034baa59b88839841ab24',
    messagingSenderId: '805423906733',
    projectId: 'gram-yatra-cb95d',
    storageBucket: 'gram-yatra-cb95d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOWB9eUEUrrugSjg4xqK_rlb9nck6Kz-U',
    appId: '1:805423906733:ios:ddc1e2d1120abda041ab24',
    messagingSenderId: '805423906733',
    projectId: 'gram-yatra-cb95d',
    storageBucket: 'gram-yatra-cb95d.firebasestorage.app',
    iosBundleId: 'com.example.gramYatra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOWB9eUEUrrugSjg4xqK_rlb9nck6Kz-U',
    appId: '1:805423906733:ios:ddc1e2d1120abda041ab24',
    messagingSenderId: '805423906733',
    projectId: 'gram-yatra-cb95d',
    storageBucket: 'gram-yatra-cb95d.firebasestorage.app',
    iosBundleId: 'com.example.gramYatra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrZUnCmFcZI22xj2D1jPnGxmmA9Fusr8U',
    appId: '1:805423906733:web:7dadd45c2df541ce41ab24',
    messagingSenderId: '805423906733',
    projectId: 'gram-yatra-cb95d',
    authDomain: 'gram-yatra-cb95d.firebaseapp.com',
    storageBucket: 'gram-yatra-cb95d.firebasestorage.app',
    measurementId: 'G-MZSRWZ4CRP',
  );

}